global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: "lab"

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["localhost:9113"]
